spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect:  org.hibernate.dialect.PostgreSQL95Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/image-gallery
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver


